# Generated by Django 2.0 on 2017-12-05 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_to', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to=settings.AUTH_USER_MODEL, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='represented_users', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'User representative',
                'verbose_name_plural': 'User representatives',
                'permissions': (('can_support', 'Can support users by switching perspective'),),
            },
        ),
    ]
